name: E2E

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
      - name: "Test kubectl get pods"
        run: |
          curl -L https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.8.3/clusterctl-linux-amd64 -o clusterctl
          sudo chmod +x clusterctl
          sudo mv clusterctl /usr/bin/clusterctl
          clusterctl version

          # Install Metal LB for exposing Kubevirt based Workload Cluster's Api server
          METALLB_VER=$(curl "https://api.github.com/repos/metallb/metallb/releases/latest" | jq -r ".tag_name")
          kubectl apply -f "https://raw.githubusercontent.com/metallb/metallb/${METALLB_VER}/config/manifests/metallb-native.yaml"
          kubectl wait pods -n metallb-system -l app=metallb,component=controller --for=condition=Ready --timeout=10m
          kubectl wait pods -n metallb-system -l app=metallb,component=speaker --for=condition=Ready --timeout=2m

          GW_IP=$(docker network inspect -f '{{range .IPAM.Config}}{{.Gateway}}{{end}}' kind)
          NET_IP=$(echo ${GW_IP} | sed -E 's|^([0-9]+\.[0-9]+)\..*$|\1|g')
          cat <<EOF | sed -E "s|172.19|${NET_IP}|g" | kubectl apply -f -
          apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            name: capi-ip-pool
            namespace: metallb-system
          spec:
            addresses:
            - 172.19.255.200-172.19.255.250
          ---
          apiVersion: metallb.io/v1beta1
          kind: L2Advertisement
          metadata:
            name: empty
            namespace: metallb-system
          EOF

          # get KubeVirt version
          KV_VER=$(curl "https://api.github.com/repos/kubevirt/kubevirt/releases/latest" | jq -r ".tag_name")
          # deploy required CRDs
          kubectl apply -f "https://github.com/kubevirt/kubevirt/releases/download/${KV_VER}/kubevirt-operator.yaml"
          # deploy the KubeVirt custom resource
          kubectl apply -f "https://github.com/kubevirt/kubevirt/releases/download/${KV_VER}/kubevirt-cr.yaml"
          kubectl wait -n kubevirt kv kubevirt --for=condition=Available --timeout=10m

          mkdir ~/.cluster-api
          touch ~/.cluster-api/clusterctl.yaml
          cat <<EOF > ~/.cluster-api/clusterctl.yaml
          providers:
          - name: "kamaji"
            url: "https://github.com/clastix/cluster-api-control-plane-provider-kamaji/releases/v0.11.0/control-plane-components.yaml"
            type: "ControlPlaneProvider"
          EOF

          cat ~/.cluster-api/clusterctl.yaml
          
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          sudo chmod 700 get_helm.sh
          ./get_helm.sh
          helm version

          helm repo add jetstack https://charts.jetstack.io
          helm repo update
          helm install \
            cert-manager jetstack/cert-manager \
            --namespace cert-manager \
            --create-namespace \
            --version v1.11.0 \
            --set installCRDs=true

          helm repo add clastix https://clastix.github.io/charts
          helm repo update
          helm install kamaji clastix/kamaji -n kamaji-system --create-namespace

          clusterctl init --infrastructure kubevirt --control-plane kamaji

          cat <<EOF > targetcluster.yaml
          apiVersion: cluster.x-k8s.io/v1beta1
          kind: Cluster
          metadata:
            name: capi-quickstart
            namespace: default
          spec:
            clusterNetwork:
              pods:
                cidrBlocks:
                - 10.243.0.0/16
              services:
                cidrBlocks:
                - 10.95.0.0/16
            controlPlaneRef:
              apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
              kind: KamajiControlPlane
              name: capi-quickstart-kubevirt
              namespace: default
            infrastructureRef:
              apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
              kind: KubevirtCluster
              name: capi-quickstart
              namespace: default
          ---
          apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
          kind: KubevirtCluster
          metadata:
            annotations:
              cluster.x-k8s.io/managed-by: kamaji
            name: capi-quickstart
            namespace: default
          ---
          apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
          kind: KamajiControlPlane
          metadata:
            name: capi-quickstart-kubevirt
            namespace: default
          spec:
            dataStoreName: default
            addons:
              coreDNS: { }
              kubeProxy: { }
            kubelet:
              cgroupfs: systemd
              preferredAddressTypes:
              - InternalIP
              - ExternalIP
            network:
              serviceType: LoadBalancer
            deployment:
            replicas: 2
            version: 1.23.10
          ---
          apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
          kind: KubevirtMachineTemplate
          metadata:
            name: capi-quickstart-md-0
            namespace: default
          spec:
            template:
              spec:
                virtualMachineBootstrapCheck:
                  checkStrategy: ssh
                virtualMachineTemplate:
                  metadata:
                    namespace: default
                  spec:
                    runStrategy: Always
                    template:
                      spec:
                        domain:
                          cpu:
                            cores: 2
                          devices:
                            disks:
                            - disk:
                                bus: virtio
                              name: containervolume
                            networkInterfaceMultiqueue: true
                          memory:
                            guest: 4Gi
                        evictionStrategy: External
                        volumes:
                        - containerDisk:
                            image: quay.io/capk/ubuntu-2004-container-disk:v1.23.10
                          name: containervolume
          ---
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          metadata:
            name: capi-quickstart-md-0
            namespace: default
          spec:
            template:
              spec:
                joinConfiguration:
                  nodeRegistration:
                    kubeletExtraArgs: {}
          ---
          apiVersion: cluster.x-k8s.io/v1beta1
          kind: MachineDeployment
          metadata:
            name: capi-quickstart-md-0
            namespace: default
          spec:
            clusterName: capi-quickstart
            replicas: 3
            selector:
              matchLabels: null
            template:
              spec:
                bootstrap:
                  configRef:
                    apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
                    kind: KubeadmConfigTemplate
                    name: capi-quickstart-md-0
                    namespace: default
                clusterName: capi-quickstart
                infrastructureRef:
                  apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
                  kind: KubevirtMachineTemplate
                  name: capi-quickstart-md-0
                  namespace: default
                version: v1.23.10
            EOF

            kubectl apply -f targetcluster.yaml
            sleep 100
            kubectl get tcp -A
            kubectl get cluster -A
            kubectl get secret -n default -o yaml
            kubectl get KamajiControlPlane -A
            kubectl get machines -A
            kubectl get svc -o yaml
